### PR TITLE
Edge trait

### PR DESCRIPTION
**Pull request by wks**
Note that this commit does not add support for compressed OOPs.

See also: https://github.com/mmtk/mmtk-core/pull/606

### CODE REVIEW

**Comment by wks** [comment]
At this stage, I simply set `OpenJDK::VMEdge` to `Address` so that it does not change the behaviour.

Microbenchmark shows the performance impact is negligible.

Benchmark: Create a 22-level binary search tree, run `System.gc()` 10 times for warmup, and run `System.gc()` 100 times to record the GC time.  Repeat the experiment for 5 times, alternating between two builds (master and this PR) and two plans (SemiSpace and Immix).  Collect all 500 GC times for each build+plan combination and see their distributions.  The code is available at https://github.com/wks/tracetest

It is run on `elk.moma`.  The command is: `MMTK_THREADS=1 RUST_BACKTRACE=1 MMTK_PLAN=$plan /path/to/java -XX:+UseThirdPartyHeap -server -XX:-TieredCompilation -Xcomp -XX:MetaspaceSize=100M -Xm{s,x}500M TraceTest $depth $gcs $warmups`.

|plan|GC|mean:1|mean:2|+-|median:1|median:2|+-|sd:1|sd:2|
|---|---|---|---|---|---|---|---|---|---|
|SemiSpace|500|130.850331838ms|130.49742917ms|99.73030051735986%|130.25169ms|129.9837085ms|99.79425871556829%|1.9529565621904863ms|1.7784804514583266ms|
|Immix|500|183.50406285ms|185.00186711199999ms|100.81622403272037%|182.564638ms|183.971054ms|100.77036605522697%|4.910330121951998ms|4.992484211050324ms|

Distribution:
image

Given that there is no performance degradation, I'll continue with other bindings.

**Comment by wks** [comment]
And the results on DaCapo Chopin. Run on `elk.moma`, 20 iterations.

Results for SemiSpace ([on squirrel.moma](https://squirrel.anu.edu.au/plotty/wks/noproject/#0|elk-2022-08-18-Thu-183244&benchmark^build^invocation^iteration^ix&GC^time.stw&|10&iteration^1^4&ix^1^null|20&1^invocation|30&1&benchmark&build;jdk-mmtk-build1|41&Histogram%20(with%20CI)^build^benchmark&))

image

Results for Immix ([on squirrel.moma](https://squirrel.anu.edu.au/plotty/wks/noproject/#0|elk-2022-08-18-Thu-183244&benchmark^build^invocation^iteration^ix&GC^time.stw&|10&iteration^1^4&ix^1^1|20&1^invocation|30&1&benchmark&build;jdk-mmtk-build1|41&Histogram%20(with%20CI)^build^benchmark&))

image

The mean STW times of most benchmarks are less than 1% different from master.  Batik has huge error bars because GC only happened on average 3 times for SemiSpace and 1.6 times for Immix.  H2 is a bit strange because in the 20 invocations, only 4 has results for SemiSpace and 2 has results for Immix, and I think the rest of the invocations failed silently for some reasons.

STW time distribution:

image

**Review by qinsoon — APPROVED** [review]
LGTM

**Review by wenyuzhao — APPROVED** [review]
LGTM.

Sorry I haven't fully addressed my compressed pointer performance issue, so I haven't try using this change to support compressed pointers. I'll probably do that later after this PR is merged.

**Pull request merged**
