### PR TITLE
Update OpenJDK to jdk-11.0.19+1-mmtk

### PR DESCRIPTION
**Pull request by k-sareen**

### CODE REVIEW

**Comment by k-sareen** [comment]
@qinsoon The newest OpenJDK version seems to pass the tests we have. The new version adds 800+ commits. Seems like it's faster in tests as well :laughing:

**Comment by k-sareen** [comment]
Oh cool the JTReg and other tests pass: https://github.com/mmtk/openjdk/actions/runs/4169674203

**Comment by caizixian** [comment]
> Oh cool the JTReg and other tests pass: https://github.com/mmtk/openjdk/actions/runs/4169674203

These aren't using third party heap.

**Comment by k-sareen** [comment]
I'm aware. But previously all the tests on the stock OpenJDK failed.

**Comment by caizixian** [comment]
We should run more correctness tests.

**Comment by k-sareen** [comment]
Ah sorry -- correction. It was only one of the Windows tests that failed previously: https://github.com/mmtk/openjdk/actions/runs/2910044308/jobs/4633857708

**Comment by caizixian** [comment]
> I'm aware. But previously all the tests on the stock OpenJDK failed.

No. They worked fine. https://github.com/mmtk/openjdk/actions/runs/3835163241

**Comment by caizixian** [comment]
> Ah sorry -- correction. It was only one of the Windows tests that failed previously: https://github.com/mmtk/openjdk/actions/runs/2910044308/jobs/4633857708

Some tests are flaky. They break on upstream repos as well.

**Comment by k-sareen** [comment]
> No. They worked fine. https://github.com/mmtk/openjdk/actions/runs/3835163241

That's a different branch. It's the LXR branch. And yes we should run the OpenJDK correctness CI for MMTk GCs for at least Linux

**Comment by k-sareen** [comment]
Performance results for GenImmix on the two JDK versions: [Internal link](http://squirrel.anu.edu.au/plotty/kunals/bench-test/p/dE8EGf)

**Review by qinsoon — APPROVED** [review]

**Pull request merged**
