### PR TITLE
Fix object copy performance

### PR DESCRIPTION
**Pull request by wenyuzhao**
This PR fixes the _get object size_ and _object copy_ performance problem in openjdk binding.

Benchmark: http://squirrel.anu.edu.au/plotty-public/wenyuz/v8/p/DVJQ9J _~2% faster on time.stw_

### CODE REVIEW

**Review by qinsoon — APPROVED** [review]
LGTM. What is the expected performance improvement from this PR?

**Comment by wenyuzhao** [comment]
> LGTM. What is the expected performance improvement from this PR?

Thanks! Haven't measured the performance differences yet. But I guess it won't show too much improvement at the moment, due to our bad work packets load-balancing.

**Comment by qinsoon** [comment]
> > LGTM. What is the expected performance improvement from this PR?
> 
> Thanks! Haven't measured the performance differences yet. But I guess it won't show too much improvement at the moment, due to our bad work packets load-balancing.

Have you measured this change in your branch?

**Comment by wenyuzhao** [comment]
> > > LGTM. What is the expected performance improvement from this PR?
> > 
> > 
> > Thanks! Haven't measured the performance differences yet. But I guess it won't show too much improvement at the moment, due to our bad work packets load-balancing.
> 
> Have you measured this change in your branch?

Not yet. I'll do that before merging this.

**Comment by qinsoon** [comment]
> > > > LGTM. What is the expected performance improvement from this PR?
> > > 
> > > 
> > > Thanks! Haven't measured the performance differences yet. But I guess it won't show too much improvement at the moment, due to our bad work packets load-balancing.
> > 
> > 
> > Have you measured this change in your branch?
> 
> Not yet. I'll do that before merging this.

Yes please. I thought you had this measured in your branch so you knew this is a clear improvement in terms of performance. This PR introduces more code that is duplicated from the OpenJDK C++ code, which generally is bad in terms of software engineering. We would need to know that this is a worthy tradeoff. If the improvement is minor or unobservable, I would suggest not merging this.

**Comment by wenyuzhao** [comment]
Benchmark: http://squirrel.anu.edu.au/plotty-public/wenyuz/v8/p/DVJQ9J _2% faster on time.stw_

**Comment by qinsoon** [comment]
> Benchmark: http://squirrel.anu.edu.au/plotty-public/wenyuz/v8/p/DVJQ9J _2% faster on time.stw_

Looks good. Thanks for sharing the results.

**Pull request merged**
