### PR TITLE
Add new correctness CI

### PR DESCRIPTION
**Pull request by k-sareen**
This commit adds a new correctness CI which parallelizes builds and tests. It uses running-ng, the latest DaCapo snapshot, and reuses build artifacts across runs. All running-ng outputs are uploaded as artifacts at the end of the workflow.

### CODE REVIEW

**Comment by k-sareen** [comment]
I'm just checking the build works and then I'll cancel the CI so that we can cache the DaCapo benchmarks once.

**Comment by k-sareen** [comment]
Currently it's a 15 min running-ng timeout, which I thought would have been fine, but we're almost certainly hitting it for some of the benchmarks. I don't know what's the best way to improve developer turnaround time and correctness. I think maybe we have a regular CI (using `cron`) that does full correctness and for PRs we have a reduced set of benchmarks. What do you think @caizixian @qinsoon @wks?

**Comment by wks** [comment]
> Currently it's a 15 min running-ng timeout, which I thought would have been fine, but we're almost certainly hitting it for some of the benchmarks. I don't know what's the best way to improve developer turnaround time and correctness. I think maybe we have a regular CI (using `cron`) that does full correctness and for PRs we have a reduced set of benchmarks. What do you think @caizixian @qinsoon @wks?

If we introduce some kind of "watch dog" mechanism in DaCapo that "feeds the dog" between iterations, we can kill an unresponsive process at the precision of iteration instead of invocation.  If we run 5 iterations per invocation, we can reduce the timeout from 15 min to 3 min.

**Comment by k-sareen** [comment]
The default is running 3 iterations x 3 invocations. Perhaps we can use the `--skip-timeout` functionality in running-ng to fail early if 1 benchmark timesout?

**Comment by qinsoon** [comment]
> Currently it's a 15 min running-ng timeout

Is it the timeout for a single benchmark? That means, for one plan for 3 invocations, the worst time is 45mins. I think Github runners have a hard timeout limit of 6h. That means at maximum we can test 8 plans.

> The default is running 3 iterations x 3 invocations. Perhaps we can use the --skip-timeout functionality in running-ng to fail early if 1 benchmark times out?

It seems unnecessary to run 3 invocations. I remember I discussed this with Steve long time ago, and his response was there was no point to run a test multiple times in the CI just to catch random bugs. Running 3 iterations also may not be worth the time. If we just run 1x1, the runtime would be 1/9 of what it is now. I don't mind running more invocations. But if we would need to make the turnaround time shorter, this might be the most effective way to go.

**Comment by k-sareen** [comment]
> It seems unnecessary to run 3 invocations. I remember I discussed this with Steve long time ago, and his response was there was no point to run a test multiple times in the CI just to catch random bugs. Running 3 iterations also may not be worth the time. If we just run 1x1, the runtime would be 1/9 of what it is now. I don't mind running more invocations. But if we would need to make the turnaround time shorter, this might be the most effective way to go.

I think it's useful to do one of more iterations and more invocations (preferably both). Gives us more confidence in the correctness.

**Comment by k-sareen** [comment]
Also ***super important note*** is that the GitHub Cache expires if it hasn't been used in 7 days. The DaCapo benchmarks have been cached by forcing a solo run right above. But if the cache ever expires, we'll suddenly have 40 jobs all trying to set the cache. Either we should run a regular `cron` CI that will use the cache so that it will never expire or we add a new single job (i.e. not parallelized via matrix) just before the test matrix so that the DaCapo cache can be set only once if has expired.

**Comment by k-sareen** [comment]
> Another point is that these tests are forcing C2 and upfront compilation -- maybe we don't want to do this as we want to catch regressions in the interpreter and C1 compiler as well. Maybe we just don't provide any compiler flags? This could potentially be faster as well.

It certainly is faster to not force C2, but then we miss out on C2-only bugs like for `luindex`.

**Review by caizixian — APPROVED** [review]
LTGM. I think we should merge it and fine-tune it later.

**Pull request merged**
