### PR TITLE
Feat: get mmtk-openjdk running on Armv8 architecture 

### PR DESCRIPTION
**Pull request by ArberSephirotheca**
Here is the result running dacapo-23.8-chopin-RC1 benchmark.

```
Statistics from batik.2666.1136.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.min     total-work.time.max     total-work.time.total
13      22908.51        5333.41 1       0       inf     -inf    0.000
Total time: 28241.92 ms
Statistics from jme.1000.236.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.max     total-work.time.min     total-work.time.total   total-work.count
2       13226.87        18.80   0       -inf    inf     0.000   0
Total time: 13245.67 ms
Statistics from eclipse.2666.1171.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
36      60579   58703   1876
Statistics from sunflow.1000.37.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
1839    23654   18475   5179
Statistics from sunflow.2666.99.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
351     11888   10553   1335
Statistics from pmd.1000.291.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.max     total-work.count        total-work.time.min     total-work.time.total
90      54941.95        21901.66        -inf    0       inf     0.000
Total time: 76843.61 ms
Statistics from zxing.1000.427.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.time.max     total-work.time.total   total-work.count
236     71496.98        17846.55        129     inf     -inf    0.000   0
Total time: 89343.53 ms
Statistics from zxing.2666.1139.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.max     total-work.time.min     total-work.count        total-work.time.total
2       75339.89        512.00  -inf    inf     0       0.000
Total time: 75851.90 ms
Statistics from luindex.6000.150.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
24      5370    5292    78
Statistics from jme.6000.1416.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.time.total   total-work.time.max     total-work.count
1       13209.64        26.66   0       inf     0.000   -inf    0
Total time: 13236.30 ms
Statistics from fop.6000.144.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.max     total-work.time.total   total-work.time.min     total-work.count
21      21721.54        704.80  1       -inf    0.000   inf     0
Total time: 22426.34 ms
Statistics from tomcat.6000.330.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
30      35428   35024   404
Statistics from pmd.2666.776.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.max     total-work.time.total   total-work.time.min     total-work.count
11      56616.63        8685.73 -inf    0.000   inf     0
Total time: 65302.35 ms
Statistics from eclipse.6000.2634.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.count        total-work.time.total   total-work.time.max
2       61052.44        298.78  inf     0       0.000   -inf
Total time: 61351.23 ms
Statistics from batik.2666.1136.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.total   total-work.count        total-work.time.max     total-work.time.min
7       22962.44        2043.21 1       0.000   0       -inf    inf
Total time: 25005.65 ms
Statistics from xalan.1000.22.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.count        total-work.time.min     total-work.time.max     total-work.time.total
468     46985.19        28245.83        0       inf     -inf    0.000
Total time: 75231.03 ms
Statistics from jython.1000.48.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
825     60511   41068   19443
Statistics from jme.2666.629.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
1       6999    6952    47
Statistics from pmd.6000.1746.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.count        total-work.time.total   total-work.time.max
4       56326.50        4608.74 inf     0       0.000   -inf
Total time: 60935.24 ms
Statistics from lusearch.6000.216.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
188     13158   12497   661
Statistics from xalan.2666.59.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.count        total-work.time.total   total-work.time.min     total-work.time.max
132     44588.18        8811.60 0       0.000   inf     -inf
Total time: 53399.79 ms
Statistics from fop.2666.64.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.time.max     total-work.time.total   total-work.count
28      13653.97        1717.05 inf     -inf    0.000   0
Total time: 15371.02 ms
Statistics from batik.2666.1136.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.max     total-work.time.min     total-work.count        total-work.time.total
1       15271.70        1058.86 -inf    inf     0       0.000
Total time: 16330.56 ms
Statistics from eclipse.6000.2634.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
31      60997   59540   1457
Statistics from pmd.2666.776.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.time.max     total-work.time.total   total-work.count
23      57936.98        5148.85 inf     -inf    0.000   0
Total time: 63085.83 ms
Statistics from jme.6000.1416.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.time.total   total-work.count        total-work.time.max
1       11731.19        38.85   inf     0.000   0       -inf
Total time: 11770.04 ms
Statistics from jme.1000.236.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.min     total-work.time.max     total-work.time.total
2       13233.23        31.64   0       0       inf     -inf    0.000
Total time: 13264.88 ms
Statistics from lusearch.2666.96.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
432     13599   12690   909
Statistics from batik.1000.426.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.time.total   total-work.count        total-work.time.max
26      22883.38        6789.59 2       inf     0.000   0       -inf
Total time: 29672.97 ms
Statistics from eclipse.2666.1171.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.total   total-work.time.min     total-work.time.max
4       50981.09        1293.75 0       0       0.000   inf     -inf
Total time: 52274.84 ms
Statistics from xalan.6000.132.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.total   total-work.time.max     total-work.time.min
343     68657.36        8064.64 49      0       0.000   -inf    inf
Total time: 76722.00 ms
Statistics from eclipse.1000.439.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.total   total-work.count        total-work.time.max     total-work.time.min
31      81564.77        5037.77 1       0.000   0       -inf    inf
Total time: 86602.54 ms
Statistics from jme.6000.1416.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.max     total-work.count        total-work.time.total   total-work.time.min
1       13175.59        16.63   0       -inf    0       0.000   inf
Total time: 13192.22 ms
Statistics from graphchi.1000.187.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
1612    20067   16977   3090
Statistics from fop.6000.144.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
4       914     881     32
Statistics from xalan.2666.59.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
135     3333    3058    274
Statistics from luindex.2666.67.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
107     5972    5407    565
Statistics from h2.2666.2992.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
3       4232    3842    390
Statistics from tomcat.1000.55.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
280     47375   45265   2111
Statistics from xalan.1000.22.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.total   total-work.time.max     total-work.time.min
1417    75938.02        29106.64        255     0       0.000   -inf    inf
Total time: 105044.66 ms
Statistics from jme.1000.236.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.total   total-work.count        total-work.time.min     total-work.time.max
2       11641.00        79.13   0.000   0       inf     -inf
Total time: 11720.13 ms
Statistics from lusearch.1000.36.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
1926    21983   16174   5809
Statistics from eclipse.1000.439.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
64      61951   59806   2145
Statistics from fop.1000.24.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
116     2780    1151    1630
Statistics from zxing.2666.1139.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
1       5319    5299    20
Statistics from batik.1000.426.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
5       2308    1799    509
Statistics from pmd.2666.776.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
12      3598    2849    748
Statistics from batik.6000.2556.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.min     total-work.time.total   total-work.time.max
0       22677.99        0.00    0       0       inf     0.000   -inf
Total time: 22677.99 ms
Statistics from eclipse.2666.1171.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.total   total-work.count        total-work.time.min     total-work.time.max
5       83540.55        2429.77 0       0.000   0       inf     -inf
Total time: 85970.32 ms
Statistics from fop.2666.64.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.time.max     total-work.count        total-work.time.total
11      13881.77        2049.04 inf     -inf    0       0.000
Total time: 15930.81 ms
Statistics from biojava.2666.525.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
30      15669   14378   1290
Statistics from zxing.1000.427.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
4       5319    5286    33
Statistics from eclipse.6000.2634.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.min     total-work.time.max     total-work.time.total
0       691.81  0.00    0       0       inf     -inf    0.000
Total time: 691.81 ms
Statistics from zxing.1000.427.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.count        total-work.time.min     total-work.time.total   total-work.time.max
78      8360.66 3365.21 0       inf     0.000   -inf
Total time: 11725.87 ms
Statistics from fop.1000.24.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.total   total-work.count        total-work.time.min     total-work.time.max
195     23907.11        9013.20 34      0.000   0       inf     -inf
Total time: 32920.31 ms
Statistics from xalan.6000.132.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.time.max     total-work.time.total   total-work.count
271     67995.41        11205.42        21      inf     -inf    0.000   0
Total time: 79200.82 ms
Statistics from fop.2666.64.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.count        total-work.time.max     total-work.time.total
63      22269.45        1532.69 6       inf     0       -inf    0.000
Total time: 23802.14 ms
Statistics from jython.2666.128.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
86      19779   16033   3746
Statistics from eclipse.1000.439.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.max     total-work.time.min     total-work.count        total-work.time.total
45      83425.93        2804.78 2       -inf    inf     0       0.000
Total time: 86230.72 ms
Statistics from batik.2666.1136.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
3       2249    1774    475
Statistics from fop.2666.64.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
10      965     883     82
Statistics from pmd.6000.1746.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
5       3178    2852    326
Statistics from zxing.2666.1139.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.max     total-work.count        total-work.time.min     total-work.time.total
3       76965.54        148.80  -inf    0       inf     0.000
Total time: 77114.34 ms
Statistics from zxing.6000.2562.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
0       5547    5547    0
Statistics from batik.6000.2556.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.time.max     total-work.count        total-work.time.total
0       22967.46        0.00    0       inf     -inf    0       0.000
Total time: 22967.46 ms
Statistics from fop.6000.144.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.count        total-work.time.total   total-work.time.max     total-work.time.min
8       13436.43        597.90  0       0.000   -inf    inf
Total time: 14034.32 ms
Statistics from h2.1000.1122.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
15      7417    6324    1093
Statistics from xalan.6000.132.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.time.max     total-work.count        total-work.time.total
109     43821.13        2579.79 inf     -inf    0       0.000
Total time: 46400.92 ms
Statistics from fop.6000.144.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.max     total-work.count        total-work.time.min     total-work.time.total
9       21651.72        849.29  0       -inf    0       inf     0.000
Total time: 22501.02 ms
Statistics from zxing.1000.427.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.min     total-work.time.max     total-work.time.total
254     11382.40        14493.45        252     0       inf     -inf    0.000
Total time: 25875.85 ms
Statistics from jme.1000.236.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
1       7002    6962    39
Statistics from jme.2666.629.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.total   total-work.time.max     total-work.time.min
1       13174.72        27.47   0       0       0.000   -inf    inf
Total time: 13202.19 ms
Statistics from tomcat.2666.147.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
69      35620   35071   549
Statistics from fop.6000.144.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.max     total-work.count        total-work.time.total   total-work.time.min
4       13714.40        952.24  -inf    0       0.000   inf
Total time: 14666.64 ms
Statistics from pmd.1000.291.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.count        total-work.time.total   total-work.time.max
38      59771.84        24780.84        inf     0       0.000   -inf
Total time: 84552.68 ms
Statistics from jme.6000.1416.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.total   total-work.time.min     total-work.time.max     total-work.count
1       11774.36        153.41  0.000   inf     -inf    0
Total time: 11927.77 ms
Statistics from biojava.1000.197.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
115     16052   15056   995
Statistics from xalan.1000.22.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
402     3736    3106    630
Statistics from zxing.6000.2562.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.count        total-work.time.total   total-work.time.max
1       76901.07        31.43   0       inf     0       0.000   -inf
Total time: 76932.50 ms
Statistics from zxing.1000.427.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.count        total-work.time.min     total-work.time.total   total-work.time.max
64      75360.42        8615.69 0       inf     0.000   -inf
Total time: 83976.11 ms
Statistics from jme.2666.629.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.total   total-work.time.max     total-work.count        total-work.time.min
1       13711.31        16.58   0       0.000   -inf    0       inf
Total time: 13727.89 ms
Statistics from jython.6000.288.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
22      7407    7181    227
Statistics from xalan.2666.59.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.count        total-work.time.max     total-work.time.total
285     44485.21        6719.78 inf     0       -inf    0.000
Total time: 51204.99 ms
Statistics from zxing.2666.1139.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.time.total   total-work.time.max     total-work.count
3       76942.53        54.78   0       inf     0.000   -inf    0
Total time: 76997.31 ms
Statistics from xalan.2666.59.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.count        total-work.time.max     total-work.time.total   total-work.time.min
554     71135.90        14509.05        55      0       -inf    0.000   inf
Total time: 85644.95 ms
Statistics from biojava.6000.1182.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
13      16030   14814   1217
Statistics from pmd.1000.291.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
49      5428    3704    1724
Statistics from jme.2666.629.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.count        total-work.time.total   total-work.time.max     total-work.time.min
1       11709.63        148.04  0       0.000   -inf    inf
Total time: 11857.67 ms
Statistics from zxing.6000.2562.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.count        total-work.time.total   total-work.time.max     total-work.time.min
1       77163.66        80.69   0       0.000   -inf    inf
Total time: 77244.35 ms
Statistics from batik.6000.2556.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
2       2224    1779    445
Statistics from xalan.6000.132.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.total   total-work.time.min     total-work.count        total-work.time.max
54      44255.46        4649.04 0.000   inf     0       -inf
Total time: 48904.50 ms
Statistics from graphchi.2666.499.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
75      14171   12994   1176
Statistics from eclipse.6000.2634.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.time.total   total-work.time.max     total-work.count
1       61660.22        1135.92 inf     0.000   -inf    0
Total time: 62796.15 ms
Statistics from sunflow.6000.222.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
155     11388   10516   871
Statistics from jme.1000.236.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.max     total-work.time.min     total-work.count        total-work.time.total
1       11731.28        149.39  -inf    inf     0       0.000
Total time: 11880.67 ms
Statistics from pmd.6000.1746.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.max     total-work.time.min     total-work.count        total-work.time.total
9       55642.70        2120.48 -inf    inf     0       0.000
Total time: 57763.17 ms
Statistics from jme.6000.1416.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
1       7017    6959    59
Statistics from zxing.6000.2562.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.total   total-work.time.min     total-work.count        total-work.time.max
1       78663.75        37.89   0       0.000   inf     0       -inf
Total time: 78701.64 ms
Statistics from batik.6000.2556.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.total   total-work.time.min     total-work.time.max     total-work.count
0       15001.09        0.00    0.000   inf     -inf    0
Total time: 15001.09 ms
Statistics from zxing.2666.1139.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.time.max     total-work.time.total   total-work.count
3       76714.09        58.71   0       inf     -inf    0.000   0
Total time: 76772.79 ms
Statistics from batik.6000.2556.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.total   total-work.time.max     total-work.count        total-work.time.min
0       14758.97        0.00    0.000   -inf    0       inf
Total time: 14758.97 ms
Statistics from fop.2666.64.temurin-20.openjdk_common.mmtk_gc-GenImmix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.min     total-work.time.total   total-work.count        total-work.time.max
49      22293.83        2604.50 2       inf     0.000   0       -inf
Total time: 24898.32 ms
Statistics from batik.2666.1136.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.count        total-work.time.total   total-work.time.min     total-work.time.max
0       14939.45        0.00    0       0.000   inf     -inf
Total time: 14939.45 ms
Statistics from zxing.6000.2562.temurin-20.openjdk_common.mmtk_gc-Immix.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.count        total-work.time.max     total-work.time.total
0       77130.17        0.00    inf     0       -inf    0.000
Total time: 77130.17 ms
Statistics from xalan.2666.59.temurin-20.openjdk_common.mmtk_gc-GenCopy.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        majorGC total-work.time.total   total-work.time.min     total-work.time.max     total-work.count
709     71126.99        11724.60        137     0.000   inf     -inf    0
Total time: 82851.60 ms
Statistics from jme.2666.629.temurin-20.openjdk_common.mmtk_gc-SemiSpace.tph.ms..dacapochopin-977043f.log:
GC      time.other      time.stw        total-work.time.min     total-work.time.max     total-work.count        total-work.time.total
1       11724.74        39.15   inf     -inf    0       0.000
Total time: 11763.89 ms
Statistics from xalan.6000.132.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
60      3107    2936    171
Statistics from graphchi.6000.1122.temurin-20.openjdk_common.hotspot_gc-G1.ms.jvmti.jvmti_env..dacapochopin-977043f.log:
pauses  time    time.other      time.stw
17      14515   13108   1407
```

### CODE REVIEW

**Comment by caizixian** [comment]
@ArberSephirotheca could you have the benchmark results in a table? Maybe each row should be a benchmarks, and you can list the performance of MMTk GCs and OpenJDK GCs in columns.

**Comment by wks** [comment]
@ArberSephirotheca Hint: Here is a script for parsing the output of running DaCapo benchmarks withthe `harness_begin`/`harness_end` utilities in MMTk-core: https://github.com/mmtk/ci-perf-kit/blob/master/scripts/parse.py

You can find other CI scripts in that repo that use the `parse.py` script.

I also find Pandas quite convenient for working with tables (DataFrame).  It can do basic statistics, do plotting, and even exporting the table into the Markdown format.

We usually use https://github.com/jamesbornholt/plotty to parse and plot the results directly.  But I won't recommend that to people outside the ANU because that requires an outdated version of Python and Django.  Anyway, it is open source.

**Review by caizixian — CHANGES_REQUESTED** [review]

**Review by caizixian — COMMENTED** [review]
This PR is basically ready. Once https://github.com/mmtk/jdk/pull/1 is merged, please update this PR to change the commit hash here

https://github.com/ArberSephirotheca/mmtk-openjdk/blob/2b4388cfdf0d33fa38e5690387a69bba62dc8955/mmtk/Cargo.toml#L21C1-L21C1

then I can approve and merge this PR as well.

**Comment by caizixian** [comment]
I've separately updated the commit hash in https://github.com/mmtk/mmtk-openjdk/commit/fd84c30cabca93d0626ca2e375893247f1f1ab72

**Pull request merged**
